// server/checker/statements.mjs — the two Gateway documents, drafted from the results.
//
// Regulation 17 defines both documents, and the Planning Inspectorate asks
// for drafts of both at Gateway 2 (procedural guide 3.6.5) and the finished
// versions at Gateway 3:
//
//   statement of compliance  how the plan complies with the requirements
//                            prescribed by regulation 32; why regulation 11(4)
//                            is not engaged, if it is not; general conformity
//                            with any spatial development strategy; where the
//                            Gateway 2 advice can be inspected
//   statement of soundness   the evidence gathered to support the plan and why
//                            it would be reasonable for the examiner to conclude
//                            the plan is sound
//
// Nothing here calls the model: the entries are the rubric results arranged in
// the order the documents need, so the structure is always the same.

export const STATEMENT_NOTICE = 'Machine-drafted starting point. This draft was generated by the Local Plan Navigator prototype from the uploaded plan. It is not an assessment by the Planning Inspectorate or MHCLG and may be wrong or incomplete. Officers must check every entry against the plan and its evidence, complete the entries marked "To be completed by the authority", and remove this note before the statement is used.';

const COMPLIANCE_PARTS = [
  { heading: 'Part 1: The prescribed requirements (regulation 32)', ids: ['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'E10', 'E11', 'E12'] },
  { heading: 'Part 2: Superseded policies (regulations 11(4) and 32(b)(iii))', ids: ['A9'], note: 'If the plan supersedes no existing policy, explain here why the authority considers regulation 11(4) is not engaged.' },
  { heading: 'Part 3: General conformity with a spatial development strategy (section 15CA(2) of the Act)', ids: ['E13'] },
  { heading: 'Part 4: Where the Gateway 2 observations and advice can be inspected', ids: ['E14'] },
];

const SOUNDNESS_IDS = ['F1', 'F2', 'F3', 'F4', 'F5'];

function entry(r, note) {
  const officer = r.assessedBy === 'officer';
  return {
    id: r.id,
    ref: r.ref ?? null,
    title: r.title,
    requirement: r.requirement,
    status: r.status,
    shows: officer ? 'To be completed by the authority. The plan document alone cannot show this.' : r.finding,
    evidence: r.evidence.map((e) => ({ quote: e.quote, locator: e.locator })),
    gaps: [...r.gaps, ...(note && r.status !== 'met' ? [note] : [])],
    action: r.action ?? '',
    completeBy: officer ? 'authority' : 'check',
  };
}

export function buildStatements({ doc, results }) {
  const get = (id) => results.get(id);
  const compliance = {
    title: 'Draft statement of compliance',
    planName: doc.name,
    notice: STATEMENT_NOTICE,
    intro: [
      `This draft sets out how the proposed local plan in "${doc.name}" complies with the requirements prescribed by regulation 32 of the Town and Country Planning (Local Planning) (England) Regulations 2026, and the other information regulation 17 says a statement of compliance must contain.`,
      'At Gateway 2 the Planning Inspectorate asks for a draft statement of compliance so the assessor can see the progress made towards the prescribed requirements (procedural guide, paragraph 3.6.5). At Gateway 3 the completed statement is one of the submission documents, and the assessor uses it as a guide.',
      'For each requirement the draft says what the plan shows, where in the plan, what is missing and what to do next. Entries marked "To be completed by the authority" depend on documents and steps outside the plan.',
    ],
    parts: COMPLIANCE_PARTS.map((part) => ({
      heading: part.heading,
      entries: part.ids.map(get).filter(Boolean).map((r) => entry(r, part.note)),
    })),
  };
  const soundnessEntries = SOUNDNESS_IDS.map(get).filter(Boolean).map((r) => ({
    ...entry(r),
    questions: r.questions ?? [],
    evidenceDocuments: r.evidenceDocuments ?? [],
  }));
  const evidenceBase = [...new Map(soundnessEntries.flatMap((e) => e.evidenceDocuments).map((d) => [d.toLowerCase(), d])).values()];
  const soundness = {
    title: 'Draft statement of soundness',
    planName: doc.name,
    notice: STATEMENT_NOTICE,
    intro: [
      `This draft sets out the evidence gathered to support the proposed local plan in "${doc.name}", and how the authority considers that evidence shows it would be reasonable for the examiner to conclude that the plan is sound (regulation 17).`,
      'It is arranged by the tests of soundness in policy PM15 of the National Planning Policy Framework (August 2026): positive, appropriate, effective, consistent with national policy and, where there is a spatial development strategy, in conformity with it.',
      'For each test the draft gives the evidence the plan itself refers to, the gaps, and questions an inspector may ask. It can only see the plan, not the evidence documents, so the authority needs to add the evidence and check every entry.',
    ],
    entries: soundnessEntries,
    evidenceBase,
  };
  return { compliance, soundness };
}
